version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Install Netlify CLI
          command: sudo npm install -g netlify-cli
      - run:
          name: Deploy
          command: netlify deploy --prod --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
